---
# tasks file for db
    - name: Show info about the env this host belong to
      debug:
        msg: "This host is in {{ env }} environment!!!"
    - name: Change mongo config file
      template:
        src: mongod.conf.j2
        dest: /etc/mongod.conf
        mode: 0664
      notify: restart mongod
