---
- name: Configure Mongo DB
  hosts: db
  vars:
    mongo_bind_ip: 0.0.0.0
  become: true
  tasks:
    - name: Change mongo config file
      template:
        src: templates/mongod.conf.j2
        dest: /etc/mongod.conf
        mode: 0664
      notify: restart mongod

  handlers:
  - name: restart mongod
    become: true
    service: name=mongod state=restarted
